### PR TITLE
Fix rocm compilation of dev.cc files

### LINKED ISSUE #105: Alpaka package fails to compile for ROCm when it has only .dev.cc files
See https://github.com/cms-sw/cmssw/issues/44506

### LINKED ISSUE #44506: Alpaka package fails to compile for ROCm when it has only .dev.cc files
From https://mattermost.web.cern.ch/cms-o-and-c/pl/5dncb3ojnfgyxdd93113z6bsdw

A package with
```
`-- HeterogeneousCore
    `-- AlpakaTest
        |-- BuildFile.xml
        |-- interface
        |   `-- alpaka
        |       |-- AlpakaESTestData.h
        |       `-- TestAlgo.h
        `-- src
            `-- alpaka
                `-- TestAlgo.dev.cc
```
fails to compile `HeterogeneousCore/AlpakaTest/src/alpaka/TestAlgo.dev.cc` for ROCm backend
```
Unknow target tmp/el8_amd64_gcc12/src/HeterogeneousCore/AlpakaTest/src/alpaka/HeterogeneousCoreAlpakaTestROCmAsync/TestAlgo.dev.cc.o
```

### PR DESCRIPTION
**Pull request by ariostas**
Fixed the issue described in #105. I just changed an if statement to make it match the cuda logic.

https://github.com/cms-sw/cmssw-config/blob/95cbc7a0514813eb7797404d5f3ce1615ec40277/SCRAM/GMake/Makefile.cuda#L87

Closes #105, closes https://github.com/cms-sw/cmssw/issues/44506.

### CODE REVIEW

**Comment by ariostas** [comment]
Oops sorry @smuzaffar, I didn't see you had submitted a PR to fix this. Please close this PR if you prefer the other fix.

**Comment by smuzaffar** [comment]
test parameters:
- full_cmssw = true

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@ariostas , this change was what I tried first but then looking closely I noticed that initially we wanted to use `hipcc` as linker for `rocm` libraries that is why I came up with #106. But looks like #106 is still not complete. Change in this PR should fix #105. Once tests here are passed then I will merge it. 

I ned to check with @fwyzard  why we want to use `hipcc` for rocm libraries?

**Comment by fwyzard** [comment]
> I ned to check with @fwyzard why we want to use `hipcc` for rocm libraries?

IIRC, `hipcc` is needed to link the device code included in the object files.

**Comment by smuzaffar** [comment]
+external

**Pull request merged**
