### PR TITLE
Update 00-nvidia-drivers to check if the CUDA devices can run a kernel

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
These changes require https://github.com/cms-sw/cmsdist/pull/7419 .

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#7419

**Comment by smuzaffar** [comment]
enable gpu

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#7419

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
